name: CI of optimo using GitHub Actions
on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  test-examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    container:
      image: javierarroyo/optimo:0.1.0
      options: --group-add users
    env:
      HOME: /home/developer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: poetry install
      - name: Test examples
        run: poetry run -m unittest tests.test_examples.Test_Optimo_Examples

  