name: CI of optimo using GitHub Actions
on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  test-examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v3
      - name: Set up Python 3.11.
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install poetry and dependencies.
        run: make install-poetry-and-dependencies
      - name: Pull optimo image from registry.
        run: make pull-optimo
      - name: Install poetry dependencies and run tests.
        run: make test-examples-in-container

  